# Generated by Django 4.1.2 on 2023-06-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idproducto',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
