# Generated by Django 4.1.2 on 2023-06-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_producto_idproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='web/static/img/productos/'),
        ),
    ]
