# Generated by Django 4.1.2 on 2023-07-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='desc.', max_length=250),
            preserve_default=False,
        ),
    ]
