# Generated by Django 4.1.2 on 2023-07-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_carrito_itemcarrito_carrito_productos_carrito_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
